import type { FeedItemView, FeedPayload } from './types';

const hour = 60 * 60 * 1000;

export function createDemoFeed(now = new Date()): FeedPayload {
  const at = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * hour).toISOString();
  const entity = (
    kind: 'person' | 'company',
    name: string,
    starred = false,
  ) => ({ id: null, kind, name, starred });

  const items: FeedItemView[] = [
    {
      id: 'demo-manus-longform',
      title: '肖弘长谈：从产品取舍到组织速度，Manus 如何跨过第一个规模化门槛',
      url: 'https://example.com/demo/manus',
      sourceName: '晚点 LatePost',
      country: 'CN',
      region: '国内',
      mediaType: 'article',
      publishedAt: at(2.6),
      firstSeenAt: at(2.2),
      durationSeconds: null,
      contentChars: 12_480,
      coverUrl: null,
      summary: '这场访谈集中在三个具体选择：先把复杂能力收进一个可完成任务的产品入口；用高频用户反馈替代抽象路线争论；在团队快速扩张前，先把决策责任写清楚。对失败的讨论比愿景更有信息量，尤其是早期定位反复和交付稳定性的代价。',
      tags: ['Agent', '产品与用户', '组织与人才', '商业模式'],
      persons: ['肖弘'],
      companies: ['Manus'],
      entities: [entity('person', '肖弘'), entity('company', 'Manus', true)],
      tier: 'highlight',
      readAt: null,
      archiveRequestedAt: null,
      status: 'ok',
      rejectReason: null,
      isNewEntity: false,
      monthlyMention: { name: 'Manus', count: 4 },
      coverTone: 0,
    },
    {
      id: 'demo-nvidia-world-model',
      title: '对谈世界模型团队：机器人基础模型为什么必须从真实失败里学习',
      url: 'https://example.com/demo/world-model',
      sourceName: '张小珺｜商业访谈录',
      country: 'CN',
      region: '国内',
      mediaType: 'podcast',
      publishedAt: at(4.5),
      firstSeenAt: at(4.1),
      durationSeconds: 14_520,
      contentChars: 28_900,
      coverUrl: null,
      summary: '嘉宾把机器人模型的难点从“参数不够大”转向“真实世界反馈太稀疏”。访谈给出了数据采集、仿真迁移和失败样本回灌的具体分工，也解释了为什么团队暂时没有追求通用演示，而是把可靠完成单一长任务当作阶段目标。',
      tags: ['机器人', '基础模型', '产品与用户', '开源'],
      persons: ['刘洺堉'],
      companies: ['NVIDIA'],
      entities: [entity('person', '刘洺堉'), entity('company', 'NVIDIA')],
      tier: 'highlight',
      readAt: null,
      archiveRequestedAt: null,
      status: 'ok',
      rejectReason: null,
      isNewEntity: true,
      monthlyMention: { name: 'NVIDIA', count: 3 },
      coverTone: 1,
    },
    {
      id: 'demo-perplexity-video',
      title: 'Aravind Srinivas on competing with defaults, distribution, and the cost of trust',
      url: 'https://example.com/demo/perplexity',
      sourceName: 'Alex Kantrowitz (Big Technology)',
      country: 'US',
      region: '海外',
      mediaType: 'video',
      publishedAt: at(7.8),
      firstSeenAt: at(7.4),
      durationSeconds: 4_860,
      contentChars: 18_240,
      coverUrl: null,
      summary: 'The conversation is unusually concrete about distribution: browser defaults, repeat-query behavior, and which trust failures permanently change user habits. Srinivas also separates model quality from product reliability, arguing that citation behavior and recovery from uncertain answers matter more than benchmark wins for daily use.',
      tags: ['消费级 AI', '市场与竞争', '增长与销售', '产品与用户'],
      persons: ['Aravind Srinivas'],
      companies: ['Perplexity'],
      entities: [entity('person', 'Aravind Srinivas', true), entity('company', 'Perplexity')],
      tier: 'feed',
      readAt: null,
      archiveRequestedAt: null,
      status: 'ok',
      rejectReason: null,
      isNewEntity: false,
      monthlyMention: { name: 'Perplexity', count: 5 },
      coverTone: 2,
    },
    {
      id: 'demo-new-founder',
      title: 'The tiny team building memory infrastructure for long-running AI agents',
      url: 'https://example.com/demo/memory-agents',
      sourceName: 'Y Combinator',
      country: 'US',
      region: '海外',
      mediaType: 'video',
      publishedAt: at(11.5),
      firstSeenAt: at(11),
      durationSeconds: 2_340,
      contentChars: 9_620,
      coverUrl: null,
      summary: 'The founders describe why agent memory breaks after days rather than minutes, then walk through a deliberately narrow first product for support teams. The useful signal is their refusal to store everything: they prioritize reversible summaries, explicit provenance, and cheap deletion over maximal recall.',
      tags: ['Agent', '企业服务', 'AI 编程', '商业模式'],
      persons: ['Maya Chen'],
      companies: ['Keepsake Labs'],
      entities: [entity('person', 'Maya Chen'), entity('company', 'Keepsake Labs')],
      tier: 'feed',
      readAt: null,
      archiveRequestedAt: null,
      status: 'ok',
      rejectReason: null,
      isNewEntity: true,
      monthlyMention: null,
      coverTone: 3,
    },
    {
      id: 'demo-open-source',
      title: '为什么我们仍然选择开放模型权重：一次关于速度、生态和防守的复盘',
      url: 'https://example.com/demo/open-model',
      sourceName: 'AI 闹',
      country: 'CN',
      region: '国内',
      mediaType: 'article',
      publishedAt: at(25),
      firstSeenAt: at(24),
      durationSeconds: null,
      contentChars: 8_320,
      coverUrl: null,
      summary: '团队把开源视为产品节奏而非价值宣言：权重开放扩大了部署场景和外部评测，但也迫使内部更快更新工具链。文章最值得看的部分是对商业边界的说明——基础能力开放，稳定托管、企业适配和反馈闭环收费。',
      tags: ['开源', '基础模型', '商业模式', '市场与竞争'],
      persons: ['林野'],
      companies: ['Northstar AI'],
      entities: [entity('person', '林野'), entity('company', 'Northstar AI')],
      tier: 'feed',
      readAt: at(20),
      archiveRequestedAt: at(19),
      status: 'ok',
      rejectReason: null,
      isNewEntity: false,
      monthlyMention: null,
      coverTone: 4,
    },
    {
      id: 'demo-funding-folded',
      title: '某 AI 应用公司宣布完成新一轮融资，估值升至 20 亿美元',
      url: 'https://example.com/demo/funding',
      sourceName: '品玩 PingWest（硅星人）',
      country: 'CN',
      region: '国内',
      mediaType: 'article',
      publishedAt: at(5.5),
      firstSeenAt: at(5.2),
      durationSeconds: null,
      contentChars: null,
      coverUrl: null,
      summary: null,
      tags: [],
      persons: [],
      companies: ['Example AI'],
      entities: [entity('company', 'Example AI')],
      tier: 'folded',
      readAt: null,
      archiveRequestedAt: null,
      status: 'ok',
      rejectReason: 'hard_negative: 融资',
      isNewEntity: false,
      monthlyMention: null,
      coverTone: 5,
    },
    {
      id: 'demo-no-subtitles-folded',
      title: 'AI founder reacts to this week’s biggest product launches',
      url: 'https://example.com/demo/no-subtitles',
      sourceName: 'a16z',
      country: 'US',
      region: '海外',
      mediaType: 'video',
      publishedAt: at(30),
      firstSeenAt: at(29),
      durationSeconds: 480,
      contentChars: null,
      coverUrl: null,
      summary: null,
      tags: [],
      persons: [],
      companies: [],
      entities: [],
      tier: 'folded',
      readAt: at(23),
      archiveRequestedAt: null,
      status: 'needs_body',
      rejectReason: 'structural: 视频时长不足 15 分钟',
      isNewEntity: false,
      monthlyMention: null,
      coverTone: 6,
    },
  ];

  return {
    items,
    generatedAt: now.toISOString(),
    mode: 'demo',
    notice: '演示数据 · 设置 AFS_FEED_DATA_MODE=database 后读取真实 Feed',
  };
}
