import { sql } from 'drizzle-orm';
import {
  bigint,
  bigserial,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

export const itemTier = pgEnum('item_tier', ['highlight', 'feed', 'folded']);

export interface TierReason {
  sourceWeight: number;
  titleSignal: number;
  admissionConfidence: number;
  entityStarred: number;
  [key: string]: number;
}

export const sources = pgTable(
  'source',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    url: text('url').notNull(),
    country: text('country'),
    language: text('language'),
    ingestMethod: text('ingest_method').notNull(),
    fetchMode: text('fetch_mode').notNull(),
    weight: real('weight').notNull().default(1),
    weightLocked: boolean('weight_locked').notNull().default(false),
    purity: real('purity').notNull().default(0.7),
    enabled: boolean('enabled').notNull().default(true),
    lastCheckedAt: timestamp('last_checked_at', { withTimezone: true }),
    consecutiveFailures: integer('consecutive_failures').notNull().default(0),
  },
  (table) => [
    uniqueIndex('source_url_unique').on(table.url),
    check('source_ingest_method_check', sql`${table.ingestMethod} in ('rss', 'youtube', 'podcast', 'html')`),
    check('source_fetch_mode_check', sql`${table.fetchMode} in ('full', 'discover_only')`),
    check('source_weight_check', sql`${table.weight} between 0.2 and 2.0`),
    check('source_purity_check', sql`${table.purity} between 0 and 1`),
    check('source_consecutive_failures_check', sql`${table.consecutiveFailures} >= 0`),
  ],
);

export const items = pgTable(
  'item',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sourceId: uuid('source_id')
      .notNull()
      .references(() => sources.id, { onDelete: 'restrict' }),

    // Facts copied from the source. These values are not generated by AI.
    url: text('url').notNull(),
    urlCanonical: text('url_canonical').notNull(),
    externalId: text('external_id'),
    title: text('title').notNull(),
    mediaType: text('media_type').notNull(),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    durationSeconds: integer('duration_seconds'),
    contentChars: integer('content_chars'),
    coverUrl: text('cover_url'),
    simhash: bigint('simhash', { mode: 'bigint' }),

    // AI-generated fields. The UI must label summary content as "🤖 AI 摘要".
    summary: text('summary'),
    tags: text('tags').array(),
    persons: text('persons').array(),
    companies: text('companies').array(),
    isFounderInterview: boolean('is_founder_interview'),
    admissionConfidence: real('admission_confidence'),
    rejectReason: text('reject_reason'),
    modelVersion: text('model_version'),

    // Display and workflow state.
    tier: itemTier('tier').notNull().default('feed'),
    tierScore: real('tier_score'),
    tierReason: jsonb('tier_reason').$type<TierReason>(),
    readAt: timestamp('read_at', { withTimezone: true }),
    archiveRequestedAt: timestamp('archive_requested_at', { withTimezone: true }),
    archivedAt: timestamp('archived_at', { withTimezone: true }),
    status: text('status').notNull().default('ok'),
    firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('item_url_canonical_unique').on(table.urlCanonical),
    unique('item_source_external_unique').on(table.sourceId, table.externalId),
    index('item_persons_gin_idx').using('gin', table.persons),
    index('item_companies_gin_idx').using('gin', table.companies),
    index('item_tags_gin_idx').using('gin', table.tags),
    index('item_first_seen_at_idx').on(table.firstSeenAt.desc()),
    index('item_archive_queue_idx')
      .on(table.archiveRequestedAt)
      .where(sql`${table.archiveRequestedAt} is not null and ${table.archivedAt} is null`),
    check('item_media_type_check', sql`${table.mediaType} in ('article', 'video', 'podcast')`),
    check('item_status_check', sql`${table.status} in ('ok', 'needs_body', 'dead_link', 'failed')`),
    check(
      'item_admission_confidence_check',
      sql`${table.admissionConfidence} is null or ${table.admissionConfidence} between 0 and 1`,
    ),
    check('item_tier_score_check', sql`${table.tierScore} is null or ${table.tierScore} between 0 and 1`),
  ],
);

export const entities = pgTable(
  'entity',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    kind: text('kind').notNull(),
    canonicalName: text('canonical_name').notNull(),
    aliases: text('aliases').array().notNull().default(sql`'{}'::text[]`),
    firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(),
    mentionCount: integer('mention_count').notNull().default(0),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    starred: boolean('starred').notNull().default(false),
    note: text('note'),
  },
  (table) => [
    unique('entity_kind_canonical_name_unique').on(table.kind, table.canonicalName),
    index('entity_aliases_gin_idx').using('gin', table.aliases),
    check('entity_kind_check', sql`${table.kind} in ('person', 'company')`),
    check('entity_mention_count_check', sql`${table.mentionCount} >= 0`),
  ],
);

export const feedback = pgTable(
  'feedback',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    itemId: uuid('item_id')
      .notNull()
      .references(() => items.id, { onDelete: 'cascade' }),
    signal: text('signal').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('feedback_item_created_at_idx').on(table.itemId, table.createdAt.desc()),
    check(
      'feedback_signal_check',
      sql`${table.signal} in ('irrelevant', 'low_quality', 'great', 'opened_source', 'archive_requested')`,
    ),
  ],
);

export interface JobPayload {
  [key: string]: unknown;
}

export const jobs = pgTable(
  'job',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    kind: text('kind').notNull(),
    payload: jsonb('payload').$type<JobPayload>().notNull(),
    idempotencyKey: text('idempotency_key'),
    status: text('status').notNull().default('queued'),
    attempts: integer('attempts').notNull().default(0),
    maxAttempts: integer('max_attempts').notNull().default(3),
    runAfter: timestamp('run_after', { withTimezone: true }).notNull().defaultNow(),
    lastError: text('last_error'),
  },
  (table) => [
    uniqueIndex('job_idempotency_key_unique').on(table.idempotencyKey),
    index('job_claim_idx')
      .on(table.runAfter, table.id)
      .where(sql`${table.status} = 'queued'`),
    check('job_kind_check', sql`${table.kind} in ('discover', 'process', 'rescore')`),
    check('job_status_check', sql`${table.status} in ('queued', 'running', 'completed', 'failed')`),
    check('job_attempts_check', sql`${table.attempts} >= 0`),
    check('job_max_attempts_check', sql`${table.maxAttempts} > 0`),
  ],
);

export type Source = typeof sources.$inferSelect;
export type NewSource = typeof sources.$inferInsert;
export type Item = typeof items.$inferSelect;
export type NewItem = typeof items.$inferInsert;
export type Entity = typeof entities.$inferSelect;
export type Feedback = typeof feedback.$inferSelect;
export type Job = typeof jobs.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;
