create extension if not exists pg_trgm with schema extensions;

create type public.item_tier as enum ('highlight', 'feed', 'folded');

create table public.source (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text not null,
  country text,
  language text,
  ingest_method text not null check (ingest_method in ('rss', 'youtube', 'podcast', 'html')),
  fetch_mode text not null check (fetch_mode in ('full', 'discover_only')),
  weight real not null default 1.0 check (weight between 0.2 and 2.0),
  weight_locked boolean not null default false,
  purity real not null default 0.7 check (purity between 0 and 1),
  enabled boolean not null default true,
  last_checked_at timestamptz,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  constraint source_url_unique unique (url)
);

create table public.item (
  id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.source(id) on delete restrict,

  -- Facts copied from the source. These values are not generated by AI.
  url text not null,
  url_canonical text not null,
  external_id text,
  title text not null,
  media_type text not null check (media_type in ('article', 'video', 'podcast')),
  published_at timestamptz,
  duration_seconds integer,
  content_chars integer,
  cover_url text,
  simhash bigint,

  -- AI-generated fields. The UI must label summary content as "🤖 AI 摘要".
  summary text,
  tags text[],
  persons text[],
  companies text[],
  is_founder_interview boolean,
  admission_confidence real check (admission_confidence is null or admission_confidence between 0 and 1),
  reject_reason text,
  model_version text,

  -- Display and workflow state.
  tier public.item_tier not null default 'feed',
  tier_score real check (tier_score is null or tier_score between 0 and 1),
  tier_reason jsonb,
  read_at timestamptz,
  archive_requested_at timestamptz,
  archived_at timestamptz,
  status text not null default 'ok' check (status in ('ok', 'needs_body', 'dead_link', 'failed')),
  first_seen_at timestamptz not null default now(),
  constraint item_url_canonical_unique unique (url_canonical),
  constraint item_source_external_unique unique (source_id, external_id)
);

comment on column public.item.url is 'FACT: source URL; never AI generated';
comment on column public.item.title is 'FACT: source title; never AI generated';
comment on column public.item.summary is 'AI GENERATED: must be labelled as AI summary in every UI';
comment on column public.item.persons is 'AI GENERATED: best-effort extracted people';
comment on column public.item.companies is 'AI GENERATED: best-effort extracted companies';
comment on column public.item.reject_reason is 'Admission rejection reason retained for rule regression';

create index item_persons_gin_idx on public.item using gin (persons);
create index item_companies_gin_idx on public.item using gin (companies);
create index item_tags_gin_idx on public.item using gin (tags);
create index item_first_seen_at_idx on public.item (first_seen_at desc);
create index item_archive_queue_idx on public.item (archive_requested_at)
  where archive_requested_at is not null and archived_at is null;
create index item_title_trgm_idx on public.item using gin (title extensions.gin_trgm_ops);

create table public.entity (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('person', 'company')),
  canonical_name text not null,
  aliases text[] not null default '{}',
  first_seen_at timestamptz not null default now(),
  mention_count integer not null default 0 check (mention_count >= 0),
  last_seen_at timestamptz,
  starred boolean not null default false,
  note text,
  constraint entity_kind_canonical_name_unique unique (kind, canonical_name)
);

create index entity_aliases_gin_idx on public.entity using gin (aliases);
create index entity_canonical_name_trgm_idx on public.entity using gin (canonical_name extensions.gin_trgm_ops);

create table public.feedback (
  id bigserial primary key,
  item_id uuid not null references public.item(id) on delete cascade,
  signal text not null check (
    signal in ('irrelevant', 'low_quality', 'great', 'opened_source', 'archive_requested')
  ),
  created_at timestamptz not null default now()
);

create index feedback_item_created_at_idx on public.feedback (item_id, created_at desc);

create table public.job (
  id bigserial primary key,
  kind text not null check (kind in ('discover', 'process', 'rescore')),
  payload jsonb not null,
  idempotency_key text,
  status text not null default 'queued' check (status in ('queued', 'running', 'completed', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 3 check (max_attempts > 0),
  run_after timestamptz not null default now(),
  last_error text,
  constraint job_idempotency_key_unique unique (idempotency_key)
);

create index job_claim_idx on public.job (run_after, id) where status = 'queued';

-- Public is an exposed schema in Supabase. Keep every table closed until M7
-- introduces the authenticated email allowlist and operation-specific policies.
alter table public.source enable row level security;
alter table public.item enable row level security;
alter table public.entity enable row level security;
alter table public.feedback enable row level security;
alter table public.job enable row level security;

revoke all on table public.source, public.item, public.entity, public.feedback, public.job
  from anon, authenticated;
revoke all on sequence public.feedback_id_seq, public.job_id_seq
  from anon, authenticated;

grant select, insert, update, delete on table
  public.source, public.item, public.entity, public.feedback, public.job
  to service_role;
grant usage, select on sequence public.feedback_id_seq, public.job_id_seq
  to service_role;
